// This file is auto-generated by scripts/generate-api-sidebar.mjs
// Run 'pnpm docs:api' to regenerate.

import type { DefaultTheme } from 'vitepress';

export const apiSidebar: DefaultTheme.SidebarMulti = {
  '/api/': [
    {
      'text': 'API Reference',
      'items': [
        {
          'text': 'Overview',
          'link': '/api/'
        },
        {
          'text': 'Classes',
          'collapsed': true,
          'items': [
            {
              'text': 'AuthError',
              'link': '/api/classes/AuthError'
            },
            {
              'text': 'Groups',
              'link': '/api/classes/Groups'
            },
            {
              'text': 'OpenCloud',
              'link': '/api/classes/OpenCloud'
            },
            {
              'text': 'OpenCloudError',
              'link': '/api/classes/OpenCloudError'
            },
            {
              'text': 'RateLimitError',
              'link': '/api/classes/RateLimitError'
            },
            {
              'text': 'Users',
              'link': '/api/classes/Users'
            }
          ]
        },
        {
          'text': 'Interfaces',
          'collapsed': true,
          'items': [
            {
              'text': 'AssetDetails',
              'link': '/api/interfaces/AssetDetails'
            },
            {
              'text': 'AssetQuota',
              'link': '/api/interfaces/AssetQuota'
            },
            {
              'text': 'BadgeDetails',
              'link': '/api/interfaces/BadgeDetails'
            },
            {
              'text': 'CollectibleDetails',
              'link': '/api/interfaces/CollectibleDetails'
            },
            {
              'text': 'GamePassDetails',
              'link': '/api/interfaces/GamePassDetails'
            },
            {
              'text': 'GenerateThumbnailOptions',
              'link': '/api/interfaces/GenerateThumbnailOptions'
            },
            {
              'text': 'Group',
              'link': '/api/interfaces/Group'
            },
            {
              'text': 'GroupMembershipItem',
              'link': '/api/interfaces/GroupMembershipItem'
            },
            {
              'text': 'GroupPermissions',
              'link': '/api/interfaces/GroupPermissions'
            },
            {
              'text': 'GroupRole',
              'link': '/api/interfaces/GroupRole'
            },
            {
              'text': 'GroupShout',
              'link': '/api/interfaces/GroupShout'
            },
            {
              'text': 'HttpOptions',
              'link': '/api/interfaces/HttpOptions'
            },
            {
              'text': 'InventoryItem',
              'link': '/api/interfaces/InventoryItem'
            },
            {
              'text': 'JoinRequestItem',
              'link': '/api/interfaces/JoinRequestItem'
            },
            {
              'text': 'ListOptions',
              'link': '/api/interfaces/ListOptions'
            },
            {
              'text': 'OpenCloudConfig',
              'link': '/api/interfaces/OpenCloudConfig'
            },
            {
              'text': 'PrivateServerDetails',
              'link': '/api/interfaces/PrivateServerDetails'
            },
            {
              'text': 'User',
              'link': '/api/interfaces/User'
            },
            {
              'text': 'UserNotificationBody',
              'link': '/api/interfaces/UserNotificationBody'
            },
            {
              'text': 'UserNotificationPayload',
              'link': '/api/interfaces/UserNotificationPayload'
            },
            {
              'text': 'UserNotificationResponse',
              'link': '/api/interfaces/UserNotificationResponse'
            },
            {
              'text': 'UserNotificationSource',
              'link': '/api/interfaces/UserNotificationSource'
            },
            {
              'text': 'UserThumbnail',
              'link': '/api/interfaces/UserThumbnail'
            }
          ]
        },
        {
          'text': 'Type Aliases',
          'collapsed': true,
          'items': [
            {
              'text': 'AssetQuotasPage',
              'link': '/api/type-aliases/AssetQuotasPage'
            },
            {
              'text': 'AssetType',
              'link': '/api/type-aliases/AssetType'
            },
            {
              'text': 'GroupMembershipItemsPage',
              'link': '/api/type-aliases/GroupMembershipItemsPage'
            },
            {
              'text': 'GroupRolesPage',
              'link': '/api/type-aliases/GroupRolesPage'
            },
            {
              'text': 'InstanceState',
              'link': '/api/type-aliases/InstanceState'
            },
            {
              'text': 'InventoryItemAssetType',
              'link': '/api/type-aliases/InventoryItemAssetType'
            },
            {
              'text': 'InventoryItemsPage',
              'link': '/api/type-aliases/InventoryItemsPage'
            },
            {
              'text': 'JoinRequestItemsPage',
              'link': '/api/type-aliases/JoinRequestItemsPage'
            },
            {
              'text': 'NotificationType',
              'link': '/api/type-aliases/NotificationType'
            },
            {
              'text': 'Page',
              'link': '/api/type-aliases/Page'
            },
            {
              'text': 'QuotaPeriod',
              'link': '/api/type-aliases/QuotaPeriod'
            },
            {
              'text': 'QuotaType',
              'link': '/api/type-aliases/QuotaType'
            },
            {
              'text': 'SocialNetworkProfiles',
              'link': '/api/type-aliases/SocialNetworkProfiles'
            },
            {
              'text': 'SocialNetworkVisibility',
              'link': '/api/type-aliases/SocialNetworkVisibility'
            },
            {
              'text': 'ThumbnailFormat',
              'link': '/api/type-aliases/ThumbnailFormat'
            },
            {
              'text': 'ThumbnailShape',
              'link': '/api/type-aliases/ThumbnailShape'
            }
          ]
        }
      ]
    }
  ]
} as const;
